# Alacritty!


# Config

import = [".config/alacritty/catppuccin-mocha.toml"]


[shell]
program = "tmux"


[env]
TERM = "xterm-256color"


[window]
decorations = "None"
opacity = 0.9


[font]
size = 11.00


[mouse]
hide_when_typing = true
